### ISSUE TITLE
[Feature Request] Add Optional Map Marker

### ISSUE THREAD

**Issue by luxlogica** [eddiesigner/sketch-map-generator#10]
Every time I've used Map Generator I've had to manually add a map marker symbol on top of the map. While there may be a case where a marker is not needed, chances are in most instances having at least one marker placed already would be welcome. 

The ideal solution would be, if the marker were optional, and could be placed as a symbol, on top of the map - at its centre (address location). That way, it could be easily customised or replaced after placing.

**Comment by eddiesigner** [comment]
I think that feature exceeds the plugin scope because in my opinion, the people always want customized markers, so if I put a marker, they still need to change the icon and move it to the desire position and probably apply more changes, I think there is almost not difference (in time) if they do it by their own from scratch.
