### ISSUE TITLE
Error: The style can not be applied

### ISSUE THREAD

**Issue by phaistonian** [eddiesigner/sketch-map-generator#18]
Using the latest beta (47).

**Comment by eddiesigner** [comment]
Are you trying to apply a Snazzy Maps style, right? Can you paste the code you have?

**Comment by AlessioLaiso** [comment]
Hi there! I'm getting the same error, with no Snazzy Maps style:

![image](https://user-images.githubusercontent.com/7041012/31395410-9877d62c-add8-11e7-8dc2-c880be00bec1.png)
![image](https://user-images.githubusercontent.com/7041012/31395441-a174d392-add8-11e7-8921-f04a7a684358.png)

**Comment by armthethinker** [comment]
I am getting the same error. Just updated to 47 today.

**Comment by erininseattle** [comment]
Same here.  Plugin won't generate any maps in 47.

**Comment by eddiesigner** [comment]
Thanks everyone for the feedback, it seems like Sketch made some changes on the last version (47 and beta 47), for instance, they changed a method definition that the plugin uses:

https://github.com/abynim/Sketch-Headers/commit/d4f3e38cfd524f466e99731ec23f3e3ce4c1630d#diff-f93b35a9fce20d7596732854cff7f1d5R45

Anyways, the issue is already solved with the plugin version **2.0.2**:
https://github.com/eddiesigner/sketch-map-generator/releases/tag/v2.0.2

You can simply close and open Sketch again and updating the plugin from there 😄
