### ISSUE TITLE
MapBox has some issue

### ISSUE THREAD

**Issue by chanakairugal** [eddiesigner/sketch-map-generator#31]
Hi Mate.
When i try with mapbox its saying "There were an issue, please check the address settings" can u please help me out with this

**Comment by eddiesigner** [comment]
What address did you put?

**Comment by chanakairugal** [comment]
Le Morne Peninsula, Mauritius, Le Morne, Mauritius

**Comment by eddiesigner** [comment]
Did you try again? because I tried and it worked:

![screen shot 2018-09-04 at 10 13 58 pm](https://user-images.githubusercontent.com/1477503/45055395-f27eac80-b08f-11e8-90d0-5aaefd5b699f.png)

Maybe the rate limit was reached and that was the reason: https://www.mapbox.com/api-documentation/#rate-limits

**Comment by chanakairugal** [comment]
Thanks mate. it's working now. I think its with as it is like u say
