### ISSUE TITLE
Map pins not showing up after generating image

### ISSUE THREAD

**Issue by bbickle** [eddiesigner/sketch-map-generator#42]
While I am previewing my map I can see the map pins but when I generate the image they disappear. Why is that?
Also, is there a way to customize the pins to use logos, etc.?
I would also like a way to use multiple pins in the same map, like a company showing how many states or cities they are located in.

**Comment by weilinzung** [comment]
I think this is not with the map pin on the image. We should have this, also I need this.

**Comment by CamronLDNF** [comment]
Same here, when I preview a Google map, I see the red map pin. Sweet. But when I generate that Google map, the map pin is nowhere to be found. Could this be fixed? Thanks.

**Comment by eddiesigner** [comment]
Hi everyone, I think there is a misunderstanding here, the pin that appears on top of the generated image in the demo is just an image that I put as part of the design file, it's not generated by the plugin.

The pin that you see in the preview is there so you can pick a more precise location and for reference purposes.

The generated map is always centered based on the location provided so you can easily put a custom pin (or even more) afterwards if you need it. Letting people to choose a custom pin is beyond the scope of the plugin because is too specific and it would be impossible to make everyone happy (maybe you would like to use an image, a symbol, an image url, a custom size, more than one pin, etc). In this way you have a clean canvas where you can put all the custom components you might have.

Sorry guys, I hope you all understand 😅
