### ISSUE TITLE
Could you please at least change my original project structure or file name?

### ISSUE THREAD

**Issue by terence55** [eddiesigner/sketch-map-generator#43]
When I released feature 'dynamic map', I specially reminded you, then that's the second time plagiarism without any mention.
![image](https://user-images.githubusercontent.com/10277628/52769540-86a36580-306b-11e9-8450-b36ec8012605.png)

Your [commit on 20 Aug 2017](https://github.com/eddiesigner/sketch-map-generator/commit/9fd12a611e708035ad017f06474904d7ee80707f) copied my [commit on 11 Aug 2017](https://github.com/terence55/sketch-map-creator/commit/8991ab96c305ccc0e61912a767db662baf6a318f)

Same project structure and some same code, just change method or parameter name.

e.g.
![image](https://user-images.githubusercontent.com/10277628/52782069-1a375f00-3089-11e9-97dc-a729dab0a855.png)

![image](https://user-images.githubusercontent.com/10277628/52782112-3935f100-3089-11e9-95cb-31b61440bb67.png)

---

Now it happened again. This time you remove my control-index-design, but not change file name, and I can still find the similar code.

![image](https://user-images.githubusercontent.com/10277628/52783131-ea3d8b00-308b-11e9-8307-f2b172886531.png)

---

![image](https://user-images.githubusercontent.com/10277628/52783064-a8ace000-308b-11e9-964e-aec3444e7803.png)

![image](https://user-images.githubusercontent.com/10277628/52783079-b2cede80-308b-11e9-854e-9f452621a737.png)

---

![image](https://user-images.githubusercontent.com/10277628/52771541-1d265580-3071-11e9-84cd-ed8ff9993743.png)

![image](https://user-images.githubusercontent.com/10277628/52771552-257e9080-3071-11e9-94d3-aec038df83e5.png)

As we all know, we are in an open source community, you can copy and use any code in MIT, but just copy and change method or parameter name, and then make it as your own product, that would make author uncomfortable, and is not a good practice.

**Comment by eddiesigner** [comment]
@terence55 I started this project on `Dec 22, 2016` mewanwhile you on `Aug 11, 2017`, so you can't talk about "plagiarism", in any case, your plugin is a "plagiarism" of mine since I was the first person who came with this idea.

I haven't seen your "first reminder", I don't know where did you put it.

The structure of my code is like that since long time ago, I haven't heard about your plugin by that time so please stop saying that I copied your "code structure".

I did the "dynamic map feature" no because of you, I did it because I got emails from people asking me for that feature. 

Is funny how you are trying to say that is your "code structure", for example, how should I call a function that creates a webview? should I call it `createDog`? how should I call a module that is in charge of everything related to Google stuff? should I call it `apple.js`? I don't think so.

When I was working on the latest version of my plugin I took inspiration from this post: [https://www.smashingmagazine.com/2017/08/create-sketch-plugin-front-end-technologies/](https://www.smashingmagazine.com/2017/08/create-sketch-plugin-front-end-technologies/)

Sorry but your plugin is irrelevant to me, I think I just discovered it some months ago and then forgot about it.

Lastly, the code within my `saveData` function was a modified version of some function I saw in the Sketch forums, by that time I haven't heard about your plugin, and more important now, as you said, that code is gone, I thought in a better solution.

I won't talk about this again since I have better things to do, please stop worring about other people and do your own stuff.
