### ISSUE TITLE
Reply to eddiesigner for map plugin

### ISSUE THREAD

**Issue by terence55** [eddiesigner/sketch-map-generator#44]
You started this project earlier than me, I admit you are the first one. But you said 'The structure of my code is like that since long time ago', it's not true definitely. 

Actually you project just has one code file 'script.cocoascript' until your commit on 20 Aug 2017. After your reconstruction, new project got to be the same structure,  same file name, same index-control-design with mine. You said your google map code file should be named 'google.js' definitely
, but not all the utility code file should be named 'common.js', actually engineers usually name it 'utils.js' or 'tools.js'. I can find several 'coincidence' in your commit. So you see, there are so many choices, you always select the most similar one. If you still insist that's coincidence, I can just said 'hehe'.

I think your new feature is based on the post you mentioned, but your commit on 20 Aug 2017, I still think it's not just by yourself. But you are right, I should stop arguing about that, it's meaningless, after all, open source is the community, the code is only a small part.

BTW, if you think your are right, why set the last issue to limited conversation, others would judge it by their common sense if I talked nonsense.

Anyway, best wish to you.

**Comment by eddiesigner** [comment]
> BTW, if you think your are right, why set the last issue to limited conversation, others would judge it by their common sense if I talked nonsense.

I locked it because I don't want to keep an endless conversation, it makes no sense. And I didn't delete it to let people read both points of view.

> You said your google map code file should be named 'google.js' definitely
> , but not all the utility code file should be named 'common.js', actually engineers usually name it 'utils.js' or 'tools.js'. I can find several 'coincidence' in your commit.

Well, I've never seen an engineer calling a file with core functions `utils.js` or `tools.js`, you use those names just for helper functions that you **may** use on different files, not for functions that are the common core of some application, that's why I called it `common.js`, I think that's even a more common practice.

I really don't like that some people just come here to write lies with no even ask first. I've been working hard on this project so many hours just because I want to help people to work faster, so because of that I find these comments to be hurtful and disrespectful.

Cheers.
