### ISSUE TITLE
Do I need to restrict Google Maps Api Key when using Map Generator in Sketch?

### ISSUE THREAD

**Issue by sreckovel** [eddiesigner/sketch-map-generator#56]
Hi, 
I've come across this issue when implementing the Google Maps api key to Map Generator in Sketch. So my question is, do I need to restrict the Google Maps Api Key and how do I do it?

Appreciate any help!

Cheers
Srecko

**Comment by eddiesigner** [comment]
Hi,

You don't need to restrict your Google Maps API Key for this plugin, actually you can't because there are no restrictions for desktop applications, only for domains and mobile apps identifiers.

You only need to make sure to follow this guide: https://github.com/eddiesigner/sketch-map-generator/wiki/How-to-generate-a-Google-Maps-key

If you generate your API Key correctly then you're ready to go.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
