### ISSUE TITLE
Mapbox shortcut

### ISSUE THREAD

**Issue by ItsMeRiley** [eddiesigner/sketch-map-generator#64]
Hi,

I updated the plugin to version 4.2.0 a few days ago and I just realized that the shortcut for Mapbox is not working, any ideas how I can fix this? 
<img width="330" alt="Screenshot 2020-12-21 at 19 31 33" src="https://user-images.githubusercontent.com/29689874/102810191-8d1b6a80-43c3-11eb-9b5f-c815fcc2a547.png">

I am running Sketch Version 70.3 (109109)

**Comment by eddiesigner** [comment]
Hi,

I will take a look on that, at the moment I don't know why it's happening, hope I can release a new version that fixes that issue or find if Sketch or another plugin is the culprit.

**Comment by eddiesigner** [comment]
I've just released [version 4.3.0](https://github.com/eddiesigner/sketch-map-generator/releases/tag/v4.3.0) which uses different shortcuts, I had to do this because `shift cmd b` didn't work for some reason, I checked the macos shortcuts, Sketch shortcuts, other plugin shortcuts and other apps shortcuts and couldn’t find that shortcut already registered so I don't really know why it doesn't work so I had no option.

From now on the plugin uses `control` in favor of `shift`, I updated the other shortcuts as well to keep it consistent.

You can see the new commands here: https://github.com/eddiesigner/sketch-map-generator#how-it-works
